[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install"

# Alle Routen auf index.html weiterleiten (SPA)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# Netlify Identity aktivieren
[template.environment]
  WEATHER_API_KEY = "DEIN_WEATHERAPI_KEY_HIER"
  
