[build]
  publish = "public"
  functions = "netlify/functions"

# Alle Routen auf index.html weiterleiten (SPA)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core" 

# Netlify Identity aktivieren
[template.environment]
  WEATHER_API_KEY = "DEIN_WEATHERAPI_KEY_HIER"
